// <auto-generated />
using System;
using AIS_LO_System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AIS_LO_System.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260402215724_RemoveModeratorRole")]
    partial class RemoveModeratorRole
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AIS_LO_System.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Administrator",
                            IsActive = true,
                            PasswordHash = "$2a$11$8KzaNdKIMyOkASKQHxSO6.bKHQAiqTpnbNYUSGBuKZRtbOWTfDXSS",
                            Role = 0,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("AIS_LO_System.Models.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssessmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LOsLockedByOutline")
                        .HasColumnType("bit");

                    b.Property<int>("MarksPercentage")
                        .HasColumnType("int");

                    b.Property<string>("SelectedLearningOutcomeIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Trimester")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("AIS_LO_System.Models.AssignmentFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignmentId")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.ToTable("AssignmentFiles");
                });

            modelBuilder.Entity("AIS_LO_System.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanEditLO")
                        .HasColumnType("bit");

                    b.Property<bool>("CanReuploadOutline")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("LecturerId")
                        .HasColumnType("int");

                    b.Property<int?>("ModeratorId")
                        .HasColumnType("int");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Trimester")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LecturerId");

                    b.HasIndex("ModeratorId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CanEditLO = true,
                            CanReuploadOutline = true,
                            Code = "INFO712",
                            School = "Information Technology",
                            Title = "Management Information Systems",
                            Trimester = 1,
                            Year = 2026
                        },
                        new
                        {
                            Id = 2,
                            CanEditLO = true,
                            CanReuploadOutline = true,
                            Code = "SOFT703",
                            School = "Information Technology",
                            Title = "Web Applications Development",
                            Trimester = 1,
                            Year = 2026
                        },
                        new
                        {
                            Id = 3,
                            CanEditLO = true,
                            CanReuploadOutline = true,
                            Code = "COMP720",
                            School = "Information Technology",
                            Title = "Information Technology Project",
                            Trimester = 1,
                            Year = 2026
                        },
                        new
                        {
                            Id = 4,
                            CanEditLO = true,
                            CanReuploadOutline = true,
                            Code = "COMP701",
                            School = "Information Technology",
                            Title = "Software Engineering",
                            Trimester = 2,
                            Year = 2026
                        },
                        new
                        {
                            Id = 5,
                            CanEditLO = true,
                            CanReuploadOutline = true,
                            Code = "COMP703",
                            School = "Information Technology",
                            Title = "Web App Dev (ASP.NET)",
                            Trimester = 2,
                            Year = 2026
                        },
                        new
                        {
                            Id = 6,
                            CanEditLO = true,
                            CanReuploadOutline = true,
                            Code = "COMP610",
                            School = "Information Technology",
                            Title = "Database Systems",
                            Trimester = 1,
                            Year = 2025
                        },
                        new
                        {
                            Id = 7,
                            CanEditLO = true,
                            CanReuploadOutline = true,
                            Code = "COMP611",
                            School = "Information Technology",
                            Title = "Systems Analysis",
                            Trimester = 1,
                            Year = 2025
                        },
                        new
                        {
                            Id = 8,
                            CanEditLO = true,
                            CanReuploadOutline = true,
                            Code = "INFO600",
                            School = "Information Technology",
                            Title = "Intro to IT",
                            Trimester = 2,
                            Year = 2024
                        });
                });

            modelBuilder.Entity("AIS_LO_System.Models.CriterionLOMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LearningOutcomeId")
                        .HasColumnType("int");

                    b.Property<int>("RubricCriterionId")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("LearningOutcomeId");

                    b.HasIndex("RubricCriterionId");

                    b.ToTable("CriterionLOMappings");
                });

            modelBuilder.Entity("AIS_LO_System.Models.LearningOutcome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LearningOutcomeText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LearningOutcomes");
                });

            modelBuilder.Entity("AIS_LO_System.Models.LecturerCourseEnrolment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId", "CourseId")
                        .IsUnique();

                    b.ToTable("LecturerCourseEnrolments");
                });

            modelBuilder.Entity("AIS_LO_System.Models.Rubric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.ToTable("Rubrics");
                });

            modelBuilder.Entity("AIS_LO_System.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Programme")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Aarav Sharma",
                            Status = 0,
                            StudentId = "2026001"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Priya Patel",
                            Status = 0,
                            StudentId = "2026002"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "John Smith",
                            Status = 0,
                            StudentId = "2026003"
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Meera Nair",
                            Status = 0,
                            StudentId = "2026004"
                        },
                        new
                        {
                            Id = 5,
                            FullName = "Ali Khan",
                            Status = 0,
                            StudentId = "2026005"
                        });
                });

            modelBuilder.Entity("AIS_LO_System.Models.StudentAssessmentMark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssessmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMarked")
                        .HasColumnType("bit");

                    b.Property<int>("StudentRefId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentRefId");

                    b.ToTable("StudentAssessmentMarks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssessmentName = "Assignment 1",
                            CourseCode = "COMP720",
                            IsMarked = true,
                            StudentRefId = 2
                        },
                        new
                        {
                            Id = 2,
                            AssessmentName = "Assignment 1",
                            CourseCode = "COMP720",
                            IsMarked = true,
                            StudentRefId = 4
                        });
                });

            modelBuilder.Entity("AIS_LO_System.Models.StudentCourseEnrolment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId", "CourseId")
                        .IsUnique();

                    b.ToTable("StudentCourseEnrolments");
                });

            modelBuilder.Entity("AIS_LO_System.Models.StudentCriterionMark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignmentId")
                        .HasColumnType("int");

                    b.Property<decimal>("CalculatedScore")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RubricCriterionId")
                        .HasColumnType("int");

                    b.Property<int>("SelectedLevel")
                        .HasColumnType("int");

                    b.Property<int>("StudentRefId")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("RubricCriterionId");

                    b.HasIndex("StudentRefId");

                    b.ToTable("StudentCriterionMarks");
                });

            modelBuilder.Entity("RubricCriterion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CriterionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RubricId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RubricId");

                    b.ToTable("RubricCriteria");
                });

            modelBuilder.Entity("RubricLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RubricCriterionId")
                        .HasColumnType("int");

                    b.Property<string>("ScaleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RubricCriterionId");

                    b.ToTable("RubricLevels");
                });

            modelBuilder.Entity("AIS_LO_System.Models.AssignmentFile", b =>
                {
                    b.HasOne("AIS_LO_System.Models.Assignment", "Assignment")
                        .WithMany("Files")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("AIS_LO_System.Models.Course", b =>
                {
                    b.HasOne("AIS_LO_System.Models.AppUser", "Lecturer")
                        .WithMany()
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("AIS_LO_System.Models.AppUser", "Moderator")
                        .WithMany()
                        .HasForeignKey("ModeratorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Lecturer");

                    b.Navigation("Moderator");
                });

            modelBuilder.Entity("AIS_LO_System.Models.CriterionLOMapping", b =>
                {
                    b.HasOne("AIS_LO_System.Models.LearningOutcome", "LearningOutcome")
                        .WithMany("CriterionMappings")
                        .HasForeignKey("LearningOutcomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RubricCriterion", "RubricCriterion")
                        .WithMany("LOMappings")
                        .HasForeignKey("RubricCriterionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningOutcome");

                    b.Navigation("RubricCriterion");
                });

            modelBuilder.Entity("AIS_LO_System.Models.LecturerCourseEnrolment", b =>
                {
                    b.HasOne("AIS_LO_System.Models.Course", "Course")
                        .WithMany("LecturerEnrolments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AIS_LO_System.Models.AppUser", "User")
                        .WithMany("CourseEnrolments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AIS_LO_System.Models.Rubric", b =>
                {
                    b.HasOne("AIS_LO_System.Models.Assignment", "Assignment")
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("AIS_LO_System.Models.StudentAssessmentMark", b =>
                {
                    b.HasOne("AIS_LO_System.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentRefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AIS_LO_System.Models.StudentCourseEnrolment", b =>
                {
                    b.HasOne("AIS_LO_System.Models.Course", "Course")
                        .WithMany("StudentEnrolments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AIS_LO_System.Models.Student", "Student")
                        .WithMany("CourseEnrolments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AIS_LO_System.Models.StudentCriterionMark", b =>
                {
                    b.HasOne("RubricCriterion", "RubricCriterion")
                        .WithMany()
                        .HasForeignKey("RubricCriterionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AIS_LO_System.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentRefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RubricCriterion");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("RubricCriterion", b =>
                {
                    b.HasOne("AIS_LO_System.Models.Rubric", "Rubric")
                        .WithMany("Criteria")
                        .HasForeignKey("RubricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rubric");
                });

            modelBuilder.Entity("RubricLevel", b =>
                {
                    b.HasOne("RubricCriterion", "RubricCriterion")
                        .WithMany("Levels")
                        .HasForeignKey("RubricCriterionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RubricCriterion");
                });

            modelBuilder.Entity("AIS_LO_System.Models.AppUser", b =>
                {
                    b.Navigation("CourseEnrolments");
                });

            modelBuilder.Entity("AIS_LO_System.Models.Assignment", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("AIS_LO_System.Models.Course", b =>
                {
                    b.Navigation("LecturerEnrolments");

                    b.Navigation("StudentEnrolments");
                });

            modelBuilder.Entity("AIS_LO_System.Models.LearningOutcome", b =>
                {
                    b.Navigation("CriterionMappings");
                });

            modelBuilder.Entity("AIS_LO_System.Models.Rubric", b =>
                {
                    b.Navigation("Criteria");
                });

            modelBuilder.Entity("AIS_LO_System.Models.Student", b =>
                {
                    b.Navigation("CourseEnrolments");
                });

            modelBuilder.Entity("RubricCriterion", b =>
                {
                    b.Navigation("LOMappings");

                    b.Navigation("Levels");
                });
#pragma warning restore 612, 618
        }
    }
}
