// <auto-generated />
using System;
using AIS_LO_System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AIS_LO_System.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260308233606_AddStudentAssessmentMarkTable")]
    partial class AddStudentAssessmentMarkTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AIS_LO_System.Models.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssessmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelectedLearningOutcomeIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Trimester")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("AIS_LO_System.Models.AssignmentFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignmentId")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.ToTable("AssignmentFiles");
                });

            modelBuilder.Entity("AIS_LO_System.Models.CriterionLOMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LearningOutcomeId")
                        .HasColumnType("int");

                    b.Property<int>("RubricCriterionId")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("LearningOutcomeId");

                    b.HasIndex("RubricCriterionId");

                    b.ToTable("CriterionLOMappings");
                });

            modelBuilder.Entity("AIS_LO_System.Models.LearningOutcome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LearningOutcomeText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LearningOutcomes");
                });

            modelBuilder.Entity("AIS_LO_System.Models.Rubric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.ToTable("Rubrics");
                });

            modelBuilder.Entity("AIS_LO_System.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Aarav Sharma",
                            StudentId = "2026001"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Priya Patel",
                            StudentId = "2026002"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "John Smith",
                            StudentId = "2026003"
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Meera Nair",
                            StudentId = "2026004"
                        },
                        new
                        {
                            Id = 5,
                            FullName = "Ali Khan",
                            StudentId = "2026005"
                        });
                });

            modelBuilder.Entity("AIS_LO_System.Models.StudentAssessmentMark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssessmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMarked")
                        .HasColumnType("bit");

                    b.Property<int>("StudentRefId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentRefId");

                    b.ToTable("StudentAssessmentMarks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssessmentName = "Assignment 1",
                            CourseCode = "COMP720",
                            IsMarked = true,
                            StudentRefId = 2
                        },
                        new
                        {
                            Id = 2,
                            AssessmentName = "Assignment 1",
                            CourseCode = "COMP720",
                            IsMarked = true,
                            StudentRefId = 4
                        });
                });

            modelBuilder.Entity("RubricCriterion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CriterionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RubricId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RubricId");

                    b.ToTable("RubricCriteria");
                });

            modelBuilder.Entity("RubricLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RubricCriterionId")
                        .HasColumnType("int");

                    b.Property<string>("ScaleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RubricCriterionId");

                    b.ToTable("RubricLevels");
                });

            modelBuilder.Entity("AIS_LO_System.Models.AssignmentFile", b =>
                {
                    b.HasOne("AIS_LO_System.Models.Assignment", "Assignment")
                        .WithMany("Files")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("AIS_LO_System.Models.CriterionLOMapping", b =>
                {
                    b.HasOne("AIS_LO_System.Models.LearningOutcome", "LearningOutcome")
                        .WithMany("CriterionMappings")
                        .HasForeignKey("LearningOutcomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RubricCriterion", "RubricCriterion")
                        .WithMany("LOMappings")
                        .HasForeignKey("RubricCriterionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningOutcome");

                    b.Navigation("RubricCriterion");
                });

            modelBuilder.Entity("AIS_LO_System.Models.Rubric", b =>
                {
                    b.HasOne("AIS_LO_System.Models.Assignment", "Assignment")
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("AIS_LO_System.Models.StudentAssessmentMark", b =>
                {
                    b.HasOne("AIS_LO_System.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentRefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("RubricCriterion", b =>
                {
                    b.HasOne("AIS_LO_System.Models.Rubric", "Rubric")
                        .WithMany("Criteria")
                        .HasForeignKey("RubricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rubric");
                });

            modelBuilder.Entity("RubricLevel", b =>
                {
                    b.HasOne("RubricCriterion", "RubricCriterion")
                        .WithMany("Levels")
                        .HasForeignKey("RubricCriterionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RubricCriterion");
                });

            modelBuilder.Entity("AIS_LO_System.Models.Assignment", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("AIS_LO_System.Models.LearningOutcome", b =>
                {
                    b.Navigation("CriterionMappings");
                });

            modelBuilder.Entity("AIS_LO_System.Models.Rubric", b =>
                {
                    b.Navigation("Criteria");
                });

            modelBuilder.Entity("RubricCriterion", b =>
                {
                    b.Navigation("LOMappings");

                    b.Navigation("Levels");
                });
#pragma warning restore 612, 618
        }
    }
}
